# Generated by Django 6.0.2 on 2026-03-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/thumbnails/', verbose_name='Miniatura Optimizada (Auto)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='portfolio/originals/', verbose_name='Imagen'),
        ),
    ]
