# Generated by Django 6.0.2 on 2026-03-01 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_photo_thumbnail_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Proyecto')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('year', models.CharField(help_text='Ej: 2026', max_length=4, verbose_name='Año')),
                ('location', models.CharField(help_text='Ej: TOKIO / OSAKA', max_length=150, verbose_name='Locación')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción Principal')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/', verbose_name='Foto de Portada')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Si se deja vacío, aparecerá suelta en el HOME.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='portafolio.project', verbose_name='Proyecto Asignado'),
        ),
    ]
