# Generated by Django 6.0.2 on 2026-03-01 18:28

import django.db.models.deletion
import portafolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_project_photo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(blank=True, default=portafolio.models.get_default_category, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='photos', to='portafolio.category', verbose_name='Categoría'),
        ),
    ]
