# Generated by Django 6.0.2 on 2026-03-01 20:08

import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_alter_photo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Artículo')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Imagen de Portada')),
                ('content', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True, verbose_name='Contenido (Editor de Bloques)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Artículo de Blog',
                'verbose_name_plural': 'Artículos de Blog',
                'ordering': ['-published_date'],
            },
        ),
    ]
